import lexusr850 from "../assets/img/cars/latest/lexx.jpeg";
import modelsports from "../assets/img/cars/latest/modelsports.jpeg";
import nissan from "../assets/img/cars/latest/nissan.jpeg";
import golf from "../assets/img/cars/latest/golf.jpeg";
import droplight from "../assets/img/cars/latest/droplight.jpeg";
import corolla2013 from "../assets/img/cars/latest/corolla.jpeg";
import lexuses350 from "../assets/img/cars/latest/lexuses350.jpeg";
import lexusis350 from "../assets/img/cars/latest/lexusis350.jpeg";
import mercedesblack from "../assets/img/cars/latest/mercedes.jpeg";
import camrysport from "../assets/img/cars/latest/camrysport.jpeg";
import olamicars from "../assets/img/cars/latest/olamicars.jpeg";
import honda from "../assets/img/cars/latest/honda.jpeg";
import camrytokunbo from "../assets/img/cars/latest/camrytokunbo.jpeg";
import lexuses350red from "../assets/img/cars/latest/lexuses350red.jpeg";
import minibus from "../assets/img/cars/latest/minibus.png";
import cantertruck from "../assets/img/cars/latest/cantertruck.png";
import toyotacamryle from "../assets/img/cars/latest/toyotacamryle.jpeg";
import toyotacorolla from "../assets/img/cars/latest/toyotacorolla.jpeg";
import toyotatruck from "../assets/img/cars/latest/toyotatruck.png";
import toyotayaris from "../assets/img/cars/latest/toyotayaris.png";

const posts = [
  {
    picture: lexusr850,
    title: "Gray 2006, Lexus RX330. Clean Direct Tokunbo",
    rating: 4.3,
    reviews: 10,
    distance: 47,
    price: "3,200,000",
    location: "Lagos",
    model: "Lexus",
    created_at: "21 minutes ago",
    promotion: {
      type: "Urgent",
    },
  },

  {
    picture: modelsports,
    title: "2010 Model Sport",
    rating: 4.9,
    reviews: 30,
    distance: 10,
    price: "3,200,000",
    location: "Lagos",
    model: "Toyota",
    created_at: "8 hours ago",
  },
  {
    picture: nissan,
    title: "1993/Nissan Frontier Hilux ",
    rating: 4.5,
    reviews: 20,
    distance: 47,
    price: "1,000,000",
    location: "Port Harcourt",
    model: "Nissan",
    created_at: "14 hours ago",
  },
  {
    picture: golf,
    title: "Urgent sale, car must go b4 xmas day ",
    rating: 4.5,
    reviews: 5,
    distance: 14,
    price: "800,000",
    location: "Ikorodu",
    model: "Toyota",
    created_at: "14 hours ago",
    promotion: {
      type: "Urgent",
    },
  },
  {
    picture: droplight,
    title: "Crystal Clean 2002 Toyota Camry Droplight(Pay And Drive)",
    rating: 4.5,
    reviews: 5,
    distance: 20,
    price: "770,000",
    location: "Lagos",
    model: "Toyota",
    created_at: "1 day ago",
  },
  {
    picture: corolla2013,
    title: "Toyota Corolla 2013",
    rating: 4.5,
    reviews: 5,
    distance: 20,
    price: "3,700,000",
    location: "Lagos",
    model: "Toyota",
    created_at: "1 day ago",
    promotion: {
      type: "Urgent",
    },
  },
  {
    picture: lexuses350,
    title: "Registered 2008 Lexus ES350",
    rating: 3,
    reviews: 70,
    distance: 36,
    price: "3,700,000",
    location: "Abuja",
    model: "Lexus",
    created_at: "2 days ago",
  },
  {
    picture: lexusis350,
    title: "Registered 2008 Lexus IS250",
    rating: 3,
    reviews: 5,
    distance: 36,
    price: "3,100,000",
    location: "Yaba",
    model: "Lexus",
    created_at: "2 days ago",
  },
  {
    picture: mercedesblack,
    title: "Mercedes Benz E-Class 4MATIC MODEL 2008",
    rating: 3.9,
    reviews: 304.6,
    distance: 40,
    price: "2,100,000",
    location: "Lagos",
    model: "Mercedes-Benz",
    created_at: "2 days ago",
  },
  {
    picture: camrysport,
    title: "Registered 2008 Toyota Camry Sport",
    rating: 4.6,
    reviews: 10,
    distance: 40,
    price: "1,850,000",
    location: "Yaba",
    model: "Toyota",
    created_at: "2 days ago",
  },
  {
    picture: olamicars,
    title: "OLAMI CAR DELIVERY SERVICE",
    rating: 5,
    reviews: 25,
    distance: 40,
    price: "50,000",
    location: "Abuja",
    model: "Auto Insurance",
    created_at: "2 days ago",
  },
  {
    picture: honda,
    title: "2012 Honda Accord, tokunbo",
    rating: 4.0,
    reviews: 11,
    distance: 40,
    price: "2,850,000",
    location: "Ikeja",
    model: "Toyota",
    created_at: "2 days ago",
  },
  {
    picture: camrytokunbo,
    title: "2011 Toyota Camry LE, tokunbo",
    rating: 4.8,
    reviews: 11,
    distance: 40,
    price: "3,850,000",
    location: "Ikeja",
    model: "Toyota",
    created_at: "2 days ago",
  },
  {
    picture: lexuses350red,
    title: "Clean Lexus ES350",
    rating: 3,
    reviews: 5,
    distance: 100,
    price: "3,850,000",
    location: "Port Harcourt",
    model: "Toyota",
    created_at: "2 days ago",
  },
  {
    picture: minibus,
    title: "Mini bus",
    rating: 4,
    reviews: 50,
    distance: 17,
    price: "1,000,000",
    location: "Isolo",
    model: "Toyota",
    created_at: "2 days ago",
  },
  {
    picture: cantertruck,
    title: "Mitsubishi canter truck",
    rating: 4,
    reviews: 50,
    distance: 17,
    price: "1,000,000",
    location: "Isolo",
    model: "Mitsubishi",
    created_at: "2 days ago",
  },
  {
    picture: toyotacamryle,
    title: "Tokunbo 2006 Toyota Camry LE",
    rating: 5,
    reviews: 50,
    distance: 17,
    price: "2,500,000",
    location: "Yaba",
    model: "Toyota",
    created_at: "3 days ago",
  },
  {
    picture: toyotacorolla,
    title: "Registered 2008 Toyota Corolla",
    rating: 5,
    reviews: 50,
    distance: 17,
    price: "1,850,000",
    location: "Yaba",
    model: "Toyota",
    created_at: "3 days ago",
  },
  {
    picture: toyotatruck,
    title: "Toyota truck ",
    rating: 4.5,
    reviews: 20,
    distance: 17,
    price: "4,850,000",
    location: "Lagos",
    model: "Toyota",
    created_at: "3 days ago",
  },
  {
    picture: toyotayaris,
    title: "Very Clean Direct Belgium Toyota Yaris",
    rating: 4.5,
    reviews: 20,
    distance: 17,
    price: "2,000,000",
    location: "Ondo",
    model: "Toyota",
    created_at: "4 days ago",
  },
];

const images = [
  {
    original: modelsports,
    thumbnail: modelsports,
  },
  {
    original: nissan,
    thumbnail: nissan,
  },
  {
    original: golf,
    thumbnail: golf,
  },
  {
    original: droplight,
    thumbnail: droplight,
  },
  {
    original: corolla2013,
    thumbnail: corolla2013,
  },
  {
    original: lexuses350,
    thumbnail: lexuses350,
  },
  {
    original: lexusis350,
    thumbnail: lexusis350,
  },
  {
    original: mercedesblack,
    thumbnail: mercedesblack,
  },
  {
    original: camrysport,
    thumbnail: camrysport,
  },
];

const recommendedPosts = [
  {
    picture: lexusr850,
    title: "Gray 2006, Lexus RX330. Clean Direct Tokunbo",
    rating: 4.3,
    reviews: 10,
    distance: 47,
    price: "3,200,000",
    location: "Lagos",
    model: "Lexus",
    created_at: "21 minutes ago",
    promotion: {
      type: "Urgent",
    },
  },

  {
    picture: modelsports,
    title: "2010 Model Sport",
    rating: 4.9,
    reviews: 30,
    distance: 10,
    price: "3,200,000",
    location: "Lagos",
    model: "Toyota",
    created_at: "8 hours ago",
  },
  {
    picture: nissan,
    title: "1993/Nissan Frontier Hilux ",
    rating: 4.5,
    reviews: 20,
    distance: 47,
    price: "1,000,000",
    location: "Port Harcourt",
    model: "Nissan",
    created_at: "14 hours ago",
  },
  {
    picture: golf,
    title: "Urgent sale, car must go b4 xmas day ",
    rating: 4.5,
    reviews: 5,
    distance: 14,
    price: "800,000",
    location: "Ikorodu",
    model: "Toyota",
    created_at: "14 hours ago",
    promotion: {
      type: "Urgent",
    },
  },
  {
    picture: droplight,
    title: "Crystal Clean 2002 Toyota Camry Droplight(Pay And Drive)",
    rating: 4.5,
    reviews: 5,
    distance: 20,
    price: "770,000",
    location: "Lagos",
    model: "Toyota",
    created_at: "1 day ago",
  },
  {
    picture: corolla2013,
    title: "Toyota Corolla 2013",
    rating: 4.5,
    reviews: 5,
    distance: 20,
    price: "3,700,000",
    location: "Lagos",
    model: "Toyota",
    created_at: "1 day ago",
    promotion: {
      type: "Urgent",
    },
  },
  {
    picture: lexuses350,
    title: "Registered 2008 Lexus ES350",
    rating: 3,
    reviews: 70,
    distance: 36,
    price: "3,700,000",
    location: "Abuja",
    model: "Lexus",
    created_at: "2 days ago",
  },
  {
    picture: lexusis350,
    title: "Registered 2008 Lexus IS250",
    rating: 3,
    reviews: 5,
    distance: 36,
    price: "3,100,000",
    location: "Yaba",
    model: "Lexus",
    created_at: "2 days ago",
  },
  {
    picture: mercedesblack,
    title: "Mercedes Benz E-Class 4MATIC MODEL 2008",
    rating: 3.9,
    reviews: 304.6,
    distance: 40,
    price: "2,100,000",
    location: "Lagos",
    model: "Mercedes-Benz",
    created_at: "2 days ago",
  },
  {
    picture: camrysport,
    title: "Registered 2008 Toyota Camry Sport",
    rating: 4.6,
    reviews: 10,
    distance: 40,
    price: "1,850,000",
    location: "Yaba",
    model: "Toyota",
    created_at: "2 days ago",
  },
  {
    picture: olamicars,
    title: "OLAMI CAR DELIVERY SERVICE",
    rating: 5,
    reviews: 25,
    distance: 40,
    price: "50,000",
    location: "Abuja",
    model: "Auto Insurance",
    created_at: "2 days ago",
  },
  {
    picture: honda,
    title: "2012 Honda Accord, tokunbo",
    rating: 4.0,
    reviews: 11,
    distance: 40,
    price: "2,850,000",
    location: "Ikeja",
    model: "Toyota",
    created_at: "2 days ago",
  },
  
];
export default posts;
export { images, recommendedPosts };
